# Generated by Django 5.1.6 on 2025-06-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambientes',
            options={'verbose_name_plural': 'Ambientes'},
        ),
        migrations.AlterModelOptions(
            name='sensores',
            options={'verbose_name_plural': 'Sensores'},
        ),
        migrations.AlterField(
            model_name='sensores',
            name='sensor',
            field=models.CharField(choices=[('Temperatura', 'Temperatura'), ('Luminosidade', 'Luminosidade'), ('Umidade', 'Umidade'), ('Contador', 'Contador')], max_length=12),
        ),
    ]
